apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ais-data-simulator-satellite.fullname" . }}
  labels:
    {{- include "ais-data-simulator-satellite.labels" . | nindent 4 }}
data:
  # Chiavi e valori per la tua ConfigMap
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
