apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: druid-middlemanager-hpa
  namespace: druid
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: druid-middle-manager
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 0
    scaleDown:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
      stabilizationWindowSeconds: 300