apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: druid-middlemanager-hpa
  namespace: druid
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: druid-middle-manager
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60