apiVersion: druid.apache.org/v1alpha1
kind: DruidIngestion
metadata:
  name: vessel-logs-ingestion
  namespace: druid
spec:
  druidCluster: druid
  ingestion:
    type: kafka
    spec:
      ioConfig:
        type: kafka
        consumerProperties:
          bootstrap.servers: "kafka.kafka.svc.cluster.local:9092"
          group.id: "druid-consumer-group"
        topic: "vts"
        inputFormat:
          type: json
          useJsonNodeReader: false
      tuningConfig:
        type: kafka
      dataSchema:
        dataSource: "vessel_logs"
        timestampSpec:
          column: "TIMESTAMP"
          format: "iso"
        dimensionsSpec:
          dimensions:
            - { type: long, name: "MMSI" }
            - { type: long, name: "IMO" }
            - "CALLSIGN"
            - { type: long, name: "A" }
            - { type: long, name: "B" }
            - { type: long, name: "C" }
            - { type: long, name: "D" }
            - { type: double, name: "DRAUGHT" }
            - "DESTINATION"
            - "LOCODE"
            - "ZONE"
            - "ECA"
            - "SRC"
            - { type: double, name: "LATITUDE" }
            - { type: double, name: "LONGITUDE" }
            - { type: long, name: "COURSE" }
            - { type: double, name: "SPEED" }
            - "ETA_AIS"
            - { type: double, name: "DEST_LAT" }
            - { type: double, name: "DEST_LON" }
        granularitySpec:
          queryGranularity: "none"
          rollup: false
          segmentGranularity: "day"
