apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: druid-pods
  namespace: druid
  labels:
    release: kube-prometheus
spec:
  podMetricsEndpoints:
      - targetPort: 9091
        path: /metrics
        interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: druid

