apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.0.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      controller.quorum.fetch.timeout.ms: "10000"
      controller.quorum.election.timeout.ms: "12000"
      num.network.threads: 12
      queued.max.requests: 5000
    storage:
      type: persistent-claim
      size: 32Gi
      deleteClaim: false
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "6Gi"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
          namespace: kafka
    template:
      pod:
        metadata:
          labels:
            kafka-metrics: 'true'
  cruiseControl:
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
    autoRebalance:
      - mode: add-brokers
        template:
          name: my-cluster-auto-rebalancing-template
      - mode: remove-brokers
        template:
          name: my-cluster-auto-rebalancing-template
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"