apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 5
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: 32Gi
    deleteClaim: false
  jvmOptions:
    -Xms: 2048m
    -Xmx: 2048m
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 0
  roles:
    - broker
  storage:
    type: persistent-claim
    size: 32Gi
    deleteClaim: false
  jvmOptions:
    -Xms: 2048m
    -Xmx: 2048m