apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: vts
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 15
  replicas: 3
  config:
    retention.bytes: 17179869184   # 16 GiB
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sat
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 15
  replicas: 3
  config:
    retention.bytes: 17179869184   # 16 GiB
