apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: latest  # Usa una versione specifica per produzione
      helm:
        releaseName: cnpg
        valueFiles:
          - $values/helm/cloudnativepg/values.yaml
    - repoURL: https://github.com/your-username/your-repo.git  # Modifica con il tuo repository
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-database
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false