apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-cluster
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: 0.2.0  # Usa una versione specifica per produzione
      helm:
        releaseName: cnpg
        valueFiles:
          - $values/helm/cloudnativepg-cluster/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      path: helm/cloudnativepg-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-database
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true