apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: druid
  namespace: argocd
#  annotations:
#    argocd-image-updater.argoproj.io/image-list: druid=apache/druid:30.0.1
#    argocd-image-updater.argoproj.io/fooalias.update-strategy: digest
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: druid
  project: default
  sources:
    - repoURL: https://asdf2014.github.io/druid-helm
      chart: druid
      targetRevision: 31.0.5
      helm:
        valueFiles:
        - $values/helm/druid/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      path: helm/druid # Tracking additional ingress file
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true