apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: druid-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: druid-operator-system
  project: default
  sources:
    - repoURL: https://charts.datainfra.io
      chart: druid-operator
      targetRevision: latest
      helm:
        values: |
          env:
            WATCH_NAMESPACE: "druid"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true