apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: flink
  project: default
  source:
    repoURL: https://github.com/apache/flink-kubernetes-operator
    targetRevision: main
    path: helm/flink-kubernetes-operator
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true