apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flink
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: flink
  project: default
  sources:
    - repoURL: https://github.com/apache/flink-kubernetes-operator
      targetRevision: main
      path: helm/flink-kubernetes-operator
      helm:
        valueFiles:
        - $values/helm/flink/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      path: helm/flink
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - ..|.priority?
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true