apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: minio
      targetRevision: 15.0.0
      helm:
        valueFiles:
        - $values/helm/minio/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true