apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 34.2.0
      helm:
        valueFiles:
        - $values/helm/traefik/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true