apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: druid
  namespace: argocd
#  annotations:
#    argocd-image-updater.argoproj.io/image-list: druid=apache/druid:30.0.1
#    argocd-image-updater.argoproj.io/fooalias.update-strategy: digest
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: druid
  project: default
  sources:
    - repoURL: https://asdf2014.github.io/druid-helm
      chart: druid
      targetRevision: 31.0.5
      helm:
        valueFiles:
        - $values/helm/druid/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: druid-operator
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: druid-operator-system
  project: default
  sources:
    - repoURL: https://charts.datainfra.io
      chart: druid-operator
      targetRevision: latest
      helm:
        values: |
          env:
            WATCH_NAMESPACE: "druid"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: kafka
      targetRevision: 31.2.0
      helm:
        valueFiles:
        - $values/helm/kafka/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cassandra
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cassandra
  project: default
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: cassandra
      targetRevision: 12.1.1
      helm:
        valueFiles:
        - $values/helm/cassandra/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ais-data-simulator-satellite
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: sat=ghcr.io/faxatos/aquascope/ais-data-simulator-satellite:latest
    argocd-image-updater.argoproj.io/sat.update-strategy: digest
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ais-data-simulator
  project: default
  sources:
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      path: helm/ais-data-simulator-satellite
      helm:
        valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ais-data-simulator-vts
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: vts=ghcr.io/faxatos/aquascope/ais-data-simulator-vts:latest
    argocd-image-updater.argoproj.io/vts.update-strategy: digest
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ais-data-simulator
  project: default
  sources:
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      path: helm/ais-data-simulator-vts
      helm:
        valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-ui
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: operatorui=ghcr.io/faxatos/aquascope/operator-ui:latest
    argocd-image-updater.argoproj.io/operatorui.update-strategy: digest
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: operator-ui
  project: default
  sources:
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      path: helm/operator-ui
      helm:
        valueFiles:
        - values.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hdfs
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: hdfs
  project: default
  sources:
    - repoURL: https://mehrwertmacher.github.io/bigdata-charts
      chart: hdfs
      targetRevision: 1.0.1
      helm:
        valueFiles:
        - $values/helm/hdfs/values.yaml
    - repoURL: https://github.com/Faxatos/AquaScope.git
      targetRevision: main
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
---