# helmfile.yaml
repositories:
  # Repository per i chart Bitnami (Kafka, Cassandra, Flink)
  - name: bitnami
    url: "https://charts.bitnami.com/bitnami"

  # Repository ufficiale per Druid (Apache)
  - name: druid
    url: "https://asdf2014.github.io/druid-helm"

releases:
  # ---------------------------------------------------------------------------
  # Kafka
  # ---------------------------------------------------------------------------
  - name: kafka
    namespace: kafka
    createNamespace: true
    chart: bitnami/kafka
    version: ~31.1.1    # Esempio di versione (verifica la pi첫 recente)
    values:
      - kafka/values.yaml   # Se preferisci, puoi inlined qui i valori
    set:
      - name: kraft.clusterId
        value: ${KRAFT_CLUSTER_ID}
    
  # ---------------------------------------------------------------------------
  # Cassandra
  # ---------------------------------------------------------------------------
  - name: cassandra
    namespace: cassandra
    createNamespace: true
    chart: bitnami/cassandra
    version: ~12.1.0     # Esempio di versione (verifica la pi첫 recente)
    values:
      - cassandra/values.yaml
    set:
      - name: dbUser.password
        value: cassandra
    hooks:
      - events: ["postsync"]
        command: "kubectl"
        args: ["apply", "-n", "cassandra", "-f", "cassandra/cassandra-init-and-prepopulate.yaml"]
    
  # ---------------------------------------------------------------------------
  # Druid
  # ---------------------------------------------------------------------------
  - name: druid
    namespace: druid
    createNamespace: true
    chart: druid-helm/druid
    version: ~31.0.0     # Esempio di versione (verifica la pi첫 recente)
    values:
      - druid/values.yaml

  # ---------------------------------------------------------------------------
  # Flink
  # ---------------------------------------------------------------------------
#  - name: flink
#    namespace: flink
#    createNamespace: true
#    chart: bitnami/flink
#    version: ~1.4.1     # Esempio di versione (verifica la pi첫 recente)
#    values:
#      - flink/values.yaml

  - name: operator-ui
    namespace: operator-ui
    createNamespace: true
    chart: ./operator-ui
    values:
      - ./operator-ui/values.yaml

  - name: ais-data-simulator-satellite
    namespace: ais-data-simulator
    createNamespace: true
    chart: ./ais-data-simulator-satellite
    values:
      - ./ais-data-simulator-satellite/values.yaml
    
  - name: ais-data-simulator-vts
    namespace: ais-data-simulator
    chart: ./ais-data-simulator-vts
    values:
      - ./ais-data-simulator-satellite/values.yaml
